# -*- coding: utf-8 -*-
"""Dashboard

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dIOdxcChJo2YytNxA-tBAi1mDOPxyLuW
"""

import pandas as pd
import numpy as np
import streamlit as st
import plotly.express as px
import yfinance as yf

import streamlit as st
import yfinance as yf
import plotly.express as px
import pandas as pd

# --- Page Configuration ---
st.set_page_config(
    page_title="Apple Stock Dashboard",
    page_icon="🍎",
    layout="wide"
)

# --- Title ---
st.title('🍎 Apple Inc. (AAPL) Stock Price Dashboard')

# --- Data Fetching ---
@st.cache_data
def load_data(ticker, period='5y'):
    """
    Downloads and caches historical stock data from Yahoo Finance.
    """
    try:
        data = yf.download(ticker, period=period, interval='1d')
        if data.empty:
            st.error(f"No data returned for ticker: {ticker}. It might be delisted or incorrect.")
            return pd.DataFrame()
        # If columns are multi-indexed (e.g. ('AAPL','Close')), flatten them
        if isinstance(data.columns, pd.MultiIndex):
            data = data[ticker]
        return data
    except Exception as e:
        st.error(f"Error downloading data: {e}")
        return pd.DataFrame()

# We hard-code 'AAPL' to ensure we only get data for one stock
data = load_data('AAPL')

# --- Main Page Content ---
if not data.empty and len(data) > 2:
    # --- Display Key Metrics ---
    st.subheader('Key Metrics')

    # Ensure we extract scalar floats, not Series
    latest_price = float(data['Close'].iloc[-1])
    previous_day_price = float(data['Close'].iloc[-2])

    price_change = latest_price - previous_day_price
    percent_change = (price_change / previous_day_price) * 100 if previous_day_price != 0 else 0.0

    # Get 52-week high/low from the last 365 days of data
    last_year_data = data.iloc[-365:]
    high_52_week = float(last_year_data['Close'].max())
    low_52_week = float(last_year_data['Close'].min())

    # Use columns for a cleaner layout
    col1, col2, col3 = st.columns(3)
    col1.metric(
        "Latest Close Price",
        f"${latest_price:,.2f}",
        f"${price_change:,.2f} ({percent_change:.2f}%)"
    )
    col2.metric("52-Week High", f"${high_52_week:,.2f}")
    col3.metric("52-Week Low", f"${low_52_week:,.2f}")

    # --- Interactive Chart ---
    st.subheader('Price Chart (Last 5 Years)')
    fig = px.line(
        data,
        x=data.index,
        y='Close',
        title='Apple (AAPL) Closing Price',
        labels={'Close': 'Closing Price (USD)'}
    )
    fig.update_layout(
        xaxis_title='Date',
        yaxis_title='Price (USD)',
        xaxis_rangeslider_visible=True
    )

    st.plotly_chart(fig, use_container_width=True)

    # --- Data Table ---
    st.subheader('Recent Data')
    st.dataframe(data.tail(10).sort_index(ascending=False))

elif len(data) <= 2:
    st.error("Not enough data downloaded to calculate metrics. Need at least 2 days.")
else:
    st.error("Could not retrieve data for AAPL. Please check your internet connection or the ticker symbol.")

import streamlit as st
import yfinance as yf
import plotly.express as px
import plotly.graph_objects as go  # <-- ADDED: Import graph objects
import pandas as pd

# --- Page Configuration ---
st.set_page_config(
    page_title="Apple Stock Dashboard",
    page_icon="🍎",
    layout="wide"
)

# --- Title ---
st.title('🍎 Apple Inc. (AAPL) Stock Price Dashboard')

# --- Data Fetching ---
@st.cache_data
def load_data(ticker, period='5y'):
    """
    Downloads and caches historical stock data from Yahoo Finance.
    """
    try:
        data = yf.download(ticker, period=period, interval='1d')
        if data.empty:
            st.error(f"No data returned for ticker: {ticker}. It might be delisted or incorrect.")
            return pd.DataFrame()

        # --- NEW: Calculate Moving Averages ---
        data['SMA_50'] = data['Close'].rolling(window=50).mean()
        data['SMA_200'] = data['Close'].rolling(window=200).mean()
        # --- End of NEW ---

        return data
    except Exception as e:
        st.error(f"Error downloading data: {e}")
        return pd.DataFrame()

# We hard-code 'AAPL' to ensure we only get data for one stock
data = load_data('AAPL')

# --- Main Page Content ---
if not data.empty and len(data) > 2:
    # --- Display Key Metrics ---
    st.subheader('Key Metrics')

    latest_price = float(data['Close'].iloc[-1])
    previous_day_price = float(data['Close'].iloc[-2])

    price_change = latest_price - previous_day_price
    percent_change = (price_change / previous_day_price) * 100 if previous_day_price != 0 else 0.0

    last_year_data = data.iloc[-365:]
    high_52_week = float(last_year_data['Close'].max())
    low_52_week = float(last_year_data['Close'].min())

    col1, col2, col3 = st.columns(3)
    col1.metric(
        "Latest Close Price",
        f"${latest_price:,.2f}",
        f"${price_change:,.2f} ({percent_change:.2f}%)"
    )
    col2.metric("52-Week High", f"${high_52_week:,.2f}")
    col3.metric("52-Week Low", f"${low_52_week:,.2f}")

    # --- UPDATED: Interactive Chart ---
    st.subheader('Price Chart with Moving Averages')

    # We now use go.Figure() for more control
    fig = go.Figure()

    # Add the Close price trace
    fig.add_trace(go.Scatter(
        x=data.index,
        y=data['Close'],
        name='Close Price',
        line=dict(color='blue')
    ))

    # Add the 50-day SMA trace
    fig.add_trace(go.Scatter(
        x=data.index,
        y=data['SMA_50'],
        name='50-Day MA',
        line=dict(color='orange', dash='dash')
    ))

    # Add the 200-day SMA trace
    fig.add_trace(go.Scatter(
        x=data.index,
        y=data['SMA_200'],
        name='200-Day MA',
        line=dict(color='red', dash='dash')
    ))

    fig.update_layout(
        title='Apple (AAPL) Price with 50-Day & 200-Day Moving Averages',
        xaxis_title='Date',
        yaxis_title='Price (USD)',
        xaxis_rangeslider_visible=True  # Keep the handy rangeslider
    )
    # --- End of UPDATED block ---

    st.plotly_chart(fig, use_container_width=True)


    # --- Data Table ---
    st.subheader('Recent Data')
    # Show MAs in the table too
    st.dataframe(data.tail(10).sort_index(ascending=False))

elif len(data) <= 2:
    st.error("Not enough data downloaded to calculate metrics. Need at least 2 days.")
else:
    st.error("Could not retrieve data for AAPL. Please check your internet connection or the ticker symbol.")